export const FILE_STATES = Object.freeze({
  AUTHORIZED: 'AUTHORIZED',
  UPLOADED: 'UPLOADED',
  PROCESSING: 'PROCESSING',
  PROCESSED: 'PROCESSED',
  REJECTED: 'REJECTED',
  ERROR: 'ERROR',
});

export const MAX_RETRIES = 3;
