
export const FILE_STATES = Object.freeze({
  AUTHORIZED: 'AUTHORIZED',
  UPLOADED: 'UPLOADED',
  PROCESSING: 'PROCESSING',
  PROCESSED: 'PROCESSED',
  REJECTED: 'REJECTED',
  ERROR: 'ERROR',
});

export const FILE_EVENTS = Object.freeze({
  FILE_UPLOADED: 'FILE_UPLOADED',
  START_PROCESSING: 'START_PROCESSING',
  PROCESSING_SUCCESS: 'PROCESSING_SUCCESS',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  TECHNICAL_ERROR: 'TECHNICAL_ERROR',
  RETRY: 'RETRY',
});

export const MAX_RETRIES = 3;